version: '{build}'

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      WINDOWS_SDK_VERSION: "v7.0"
      VCVARSALL_PLATFORM: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      VCVARSALL_PLATFORM: amd64

install:
  - cinst ninja

build_script: |-
    %CMD_IN_ENV% .\.ci\build.cmd

artifacts:
  - path: dist\**\*
