version: '{build}'

environment:
  - WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python27"
      WINDOWS_SDK_VERSION: "v7.0"
      VCVARSALL_PLATFORM: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WINDOWS_SDK_VERSION: "v7.0"
      PYTHON: "C:\\Python27-x64"
      VCVARSALL_PLATFORM: amd64

install:
  - cinst ninja

build_script: |-
    IF %VCVARSALL_PLATFORM% == amd64 (
        ECHO Configuring Windows SDK %WINDOWS_SDK_VERSION% for Python %PYTHON% on a 64 bit architecture
        "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Setup\WindowsSdkVer.exe" -q -version:%WINDOWS_SDK_VERSION%
        "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Bin\SetEnv.cmd" /x64 /release
    ) ELSE (
        ECHO Configuring Windows SDK %WINDOWS_SDK_VERSION% for Python %PYTHON% on a 32 bit architecture
        "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Setup\WindowsSdkVer.exe" -q -version:%WINDOWS_SDK_VERSION%
        "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Bin\SetEnv.cmd" /release
    )

    "C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat" %VCVARSALL_PLATFORM%

    mkdir dist
    mkdir build
    cd build
    cmake --version
    cmake .. ^
      -DCMAKE_BUILD_TYPE=Release ^
      "-DCMAKE_C_COMPILER=C:/Users/appveyor/AppData/Local/Programs/Common/Microsoft/Visual C++ for Python/9.0/VC/bin/%VCVARSALL_PLATFORM%/cl.exe" ^
      "-DCMAKE_C_COMPILER=C:/Users/appveyor/AppData/Local/Programs/Common/Microsoft/Visual C++ for Python/9.0/VC/bin/%VCVARSALL_PLATFORM%/cl.exe" ^
      "-DCMAKE_LINKER=C:/Users/appveyor/AppData/Local/Programs/Common/Microsoft/Visual C++ for Python/9.0/VC/bin/%VCVARSALL_PLATFORM%/link.exe" ^
      -DCMAKE_INSTALL_PREFIX=..\dist ^
      -G Ninja
    cmake --build .
    cmake --build --target install .

artifacts:
  - path: dist\*
